import instrument_recognition.utils.train
import instrument_recognition.utils.audio
import instrument_recognition.utils.effects
import instrument_recognition.utils.plot
import instrument_recognition.utils.data
from instrument_recognition.utils.parser_types import *